### PR TITLE
Initial Guest Secureboot Support

### PR DESCRIPTION
**Pull request by erichte-ibm**
This PR contains a large overhaul of the secvarctl structure and code to support guest secureboot as well as host. Most of the development iterations have been done internally, which is why there are several very large commits.

This is largely still a work-in-progress effort. There are a lot of changes that need to still be made, so expect further pull requests and/or amendments to this PR as the implementation is refined from the internal development version.

Known current problems:
- [ ] root `CMakeLists.txt` does not seem to build the whole project
- [ ] `secvarctl -m guest read` does not seem to read from default path by default
- [ ] current CI fails, probably because it chokes on the submodule, new build system, and incorrect style overhaul. Has been temporarily disabledm will probably refactor after merge?

Current known post-merge TODO items:
- [ ] reformat code using `clang-format`, as was originally intended
- [ ] add CI jobs for running unit tests, static analysis, style checks, etc
- [ ] refactor directory structure (again) to reduce needless guest/host separation
- [ ] reduce build system complexity

### CODE REVIEW

**Comment by nick-child-ibm** [comment]
Not sure if this is being postponed but building with mbedtls is failing:
```
make MBEDTLS=1
In file included from host_svc_read.c:12:
../../external/host/skiboot/libstb/secvar/crypto/crypto.h:32:10: fatal error: external/extraMbedtls/include/pkcs7.h: No such file or directory
 #include "external/extraMbedtls/include/pkcs7.h"
```
looks like `external/extraMbedtls/include/pkcs7.h` should be `external/host/extraMbedtls/include/pkcs7.h`

**Comment by nick-child-ibm** [comment]
`make GNUTLS=1` actually gets to the linking step but it is also failing (and `MBEDTLS` will hit this issue as well) because `backends/guest/Makefile` does parse these values and `external/guest/libstb-secvar/Makefile` depends solely on openssl.

**Comment by nick-child-ibm** [comment]
I am only looking at Makefile changes. As CMake seems to have issues.

**Comment by nick-child-ibm** [comment]
Looks like man page needs revisiting. I suppose this can be scheduled work as well

**Comment by nick-child-ibm** [comment]
`make MEMCHECK=1` fails:
```
cat test/guest/log/verifylog.txt 
WARNING!! platform does not support secure variables
WARNING: unsupported backend detected, assuming ibm,plpks-sb-v1
read/write may not work as expected
WARNING: appended ESL is empty, (valid key reset file)...
RESULT: SUCCESS
==42845== 865 bytes in 1 blocks are definitely lost in loss record 1 of 1
==42845==    at 0x4C37135: malloc (vg_replace_malloc.c:381)
==42845==    by 0x402F72: ??? (in /home/nchild/IBM/secvarctl-stuff/final-gsb-svc/secvarctl/secvarctl-cov)
==42845==    by 0x417D0D: ??? (in /home/nchild/IBM/secvarctl-stuff/final-gsb-svc/secvarctl/secvarctl-cov)
==42845==    by 0x418047: ??? (in /home/nchild/IBM/secvarctl-stuff/final-gsb-svc/secvarctl/secvarctl-cov)
==42845==    by 0x418254: ??? (in /home/nchild/IBM/secvarctl-stuff/final-gsb-svc/secvarctl/secvarctl-cov)
==42845==    by 0x418BDE: ??? (in /home/nchild/IBM/secvarctl-stuff/final-gsb-svc/secvarctl/secvarctl-cov)
==42845==    by 0x4170D3: ??? (in /home/nchild/IBM/secvarctl-stuff/final-gsb-svc/secvarctl/secvarctl-cov)
==42845==    by 0x402940: ??? (in /home/nchild/IBM/secvarctl-stuff/final-gsb-svc/secvarctl/secvarctl-cov)
==42845==    by 0x536BD84: (below main) (in /usr/lib64/libc-2.28.so)
==42845== 


**********COMMAND RAN: $valgrind -q --error-exitcode=101 --leak-check=full /home/nchild/IBM/secvarctl-stuff/final-gsb-svc/secvarctl/secvarctl-cov -m guest verify -u KEK ./testdata/authfiles/reset_KEK_by_PK.auth -p ./testenv/
```

**Comment by nick-child-ibm** [comment]
coverage files are only being built for files built in the root `Makefile`:
```$ find . -name "*cov*"
./src/generic.cov.gcno
./src/generic.cov.d
./src/generic.cov.o
./src/secvarctl.cov.gcno
./src/secvarctl.cov.d
./src/secvarctl.cov.o
./secvarctl-cov
```

**Comment by erichte-ibm** [comment]
Closing as this will be worked on in a separate branch `guest-devel`, and tracked via #41

**Pull request closed without merging**
